#!/bin/bash

# this is a script to simplify the process of running headless vmware fusion virtual machines

# if no paramerter is enterned, check if any virtual machine is running
if [ -z "$1" ] 
  then
    vmrun list
    exit 1
fi

# the first parameter represents the actions to be taken
VMEXTRA=""
case "$1" in
  start)
    VMC="start"
    VMEXTRA="nogui"
    ;;
  stop)
    VMC="stop"
    ;;
  suspend)
    VMC="suspend"
    ;;
  pause)
    VMC="pause"
    ;;
  unpause)
    VMC="unpause"
    ;;
  restart)
    VMC="reset"
    ;;
  ip)
    VMC="getGuestIPAddress"
    VMEXTRA="-wait"
    ;;
  *)
    echo "Usage: possible options are: start | stop | suspend | pause | unpause | restart | ip"
    exit 1
esac

# if the second parameter is not inputed, ask the user to input it
if [ -z "$2" ] 
  then
    echo "Please enter the name of the virtual machine."
    # 
    exit 1
fi

# NAME: the second parameter is the name of the virtual machine
case "$2" in
  vm_name)
    VM="path_to_vmx"
    ;;
  *)
    echo "Please use a correct virtual machine name."
    exit 1
esac

# run the operation
vmrun $VMC "$VM" $VMEXTRA

# SSH: setup your ssh config after starting your vm
# if [ $1 = "start" ]
#  then 
#     VMIP=$(vm ip $2)

#     VMSTR='/Host '$2'/,/HostName/ s/HostName .*/HostName '${VMIP}'/;'

#     sed -i -n "$VMSTR" ~/.ssh/config
#     echo $VMIP
# fi
